# 06/12/2018
# Project: Elrow x Absolut
# Short script to read the json data from the text file in each folder generated by the selfie booth cathedral. The folders must be manually downloaded
# from the Dropbox account (Username: absoluttestingelrow@gmail.com, Password: thingking) and placed in the same folder from which the script is run. 
# The data is written to a csv file which must be manually uploaded to Dropbox again for the client

# Python version: Python 2.7.15
# Dependancies: none

import os, json, datetime, time, csv

folders = filter(lambda x: os.path.isdir(x), os.listdir('.'))

with open('elrow_file.csv', mode='w') as elrow_file:
    fieldnames = ['Date', 'Name', 'Email']                                                                  # Column names
    elrow_writer = csv.DictWriter(elrow_file, fieldnames=fieldnames, lineterminator = '\n')    
    elrow_writer.writeheader()                                                                              # Write column headings
    for folder in folders:
        unixTimestampFloat = float(folder)                                                                  # Unix time stamp as folder name
        unixTimestampString = str(folder)
        readableDate = time.ctime(unixTimestampFloat)                                                       # Make unix time human readable
        detailsFileDir = '.\\' + unixTimestampString + '\\' + 'details.txt'    # Directory to details.txt     
        try:
            detailsFile = open(detailsFileDir,"r")   
        except:
            print('could not open txt file:' + unixTimestampString)                                                           # Open text file
        try:
            data = json.load(detailsFile)   
        except:
            print('could not process json for ' + unixTimestampString)                                                                    # Load json data
        elrow_writer.writerow({'Date': readableDate, 'Name': data["name"], 'Email': data["email"]})         # Write row to csv file
    

    